For Release v1.0.20
* Core fixes
  * Environment variable assignment from config on startup is fixed
  * AAC selection is now random instead of always choosing first member
  * CRUD for DB UserAOCache has race condition fix for user access
  * Background write attempts of files have reduced CPU usage
  * Cache purge iteration refactored to improve peformance and logging
  * CPU and Memory allocation reported in /stats is now more accurate
  * Images in API documentation restored as well as header info
  * Normalized all time references to UTC
  * Added common uploader to handle uploaded files that initially failed
  * Service shutdown will force halt in 2.5 minutes instead of 3.5 days
* Database
  * Migration script for 20190225. This is optional for this release.
  * Service will be tolerant of both 20170726 and 20190225 schema
  * 20190225 is actually a data cleansing to repair per SAG guidance.
* Environment variables added for improved configuration
  * OD_DB_RECHECK_TIME
  * OD_USERAOCACHE_LRU_TIME
  * OD_USERAOCACHE_TIMEOUT
  * OD_PEER_ENABLED
  * OD_CACHE_FILELIMIT
  * OD_CACHE_FILESLEEP
  * OD_CACHE_LOWTHRESHOLDPERCENT
  * OD_CACHE_HIGHTHRESHOLDPERCENT
* Testing applied
  * Over 30000 unique ACMs
  * Run on 4 instances of Object Drive, as well as single instance
  * Run with 2 instances of AAC, as well as single instance
* Other
  * Added centos7 docker image to full stack
  * Added info regarding BoringCrypto integration and FIPS 140-2  to docs
  * Python scripts now work with 2.7 and 3 for future
  * Go Client now supports retrieving stream of revision
  * Captured release notes from 1.0.19
  * Versioning throughout project streamlined to base on changelog.md
  * Removed expired AlienCA1 from truststore used for development
  * Using AAC 1.2.6-SNAPSHOT and updated DIAS containers from DI2E
  * Fixed integration tests that broke due to DIAS profile changes
  * Removed various unused code, made spelling corrections
  * Assorted script improvements to allow building on a Mac
  * Add support for disabling retrieving stream from peers

Fixes DIMEODS-1146, DIME-345, DIMEODS-1236

diff --git a/docker/installui b/docker/installui
--- a/docker/installui
+++ b/docker/installui
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+ODRIVE_VERSION=$(grep -m 1 '## Release' ../changelog.md|awk '{print $3}')
+ODRIVE_VERSION_MAJOR_MINOR=$(awk '{printf "%s.%s", $1, $2}' <<< "${ODRIVE_VERSION//[^0-9]/ }")
+
 TARFILE=odrive-ui-1.2.10-2019-02-07.tar.gz
 cd $GOPATH/src/bitbucket.di2e.net/dime/object-drive-server/docker
 rm odrive-ui-*.tar.gz*
@@ -14,6 +17,14 @@ aws s3 cp s3://decipherers/$TARFILE $TARFILE
   mv dist/* opt/apps/drive/
   rm -rf dist/
   cp ../proxier/drive/settings.json opt/apps/drive/json/settings.json
+  if [[ "$OSTYPE" == "linux-gnu" ]]; then
+    sed -i s/--MajorMinorVersion--/${ODRIVE_VERSION_MAJOR_MINOR}/ opt/apps/drive/json/settings.json
+  elif [[ "$OSTYPE" == "darwin"* ]]; then
+    sed -i '' -e s/--MajorMinorVersion--/${ODRIVE_VERSION_MAJOR_MINOR}/ opt/apps/drive/json/settings.json
+  else
+    echo "Platform unknown. Unable to perform required replacements for object drive endpoint in settings.json"
+    exit 1
+  fi
   cp ../proxier/drive/chm_drive.json opt/apps/drive/json/chm_drive.json
   cp ../proxier/drive/piwik.js opt/apps/drive/json/piwik.js
   cp ../proxier/drive/piwik.php opt/apps/drive/json/piwik.php
@@ -22,3 +33,4 @@ aws s3 cp s3://decipherers/$TARFILE $TARFILE
 docker cp ui.tar docker_proxier_1:ui.tar
 docker exec docker_proxier_1 tar xvf /ui.tar
 docker exec docker_proxier_1 chown -R nginx:nginx /opt/apps
+rm -rf ui/
